// <auto-generated />
using System;
using Chinook.Repository.Postgresql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Chinook.WebApi.Migrations
{
    [DbContext(typeof(ChinookDbContext))]
    partial class ChinookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Chinook.WebApi.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnName("album_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ArtistId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(160);

                    b.HasKey("AlbumId")
                        .HasName("album__album_id__pkey");

                    b.HasIndex("ArtistId")
                        .HasName("album__artist_id__idx");

                    b.ToTable("album");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("artist_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(120);

                    b.HasKey("ArtistId")
                        .HasName("artist__artist_id__pkey");

                    b.ToTable("artist");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasMaxLength(70);

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasMaxLength(40);

                    b.Property<string>("Company")
                        .HasColumnName("company")
                        .HasMaxLength(80);

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasMaxLength(40);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(60);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasMaxLength(24);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(24);

                    b.Property<string>("PostalCode")
                        .HasColumnName("postal_code")
                        .HasMaxLength(10);

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasMaxLength(40);

                    b.Property<int>("SupportRepId");

                    b.HasKey("CustomerId")
                        .HasName("customer__customer_id__pkey");

                    b.HasIndex("SupportRepId")
                        .HasName("customer__support_rep_id__idx");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("employee_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasMaxLength(70);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnName("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasMaxLength(40);

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasMaxLength(40);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(60);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasMaxLength(24);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasMaxLength(20);

                    b.Property<DateTime>("HireDate")
                        .HasColumnName("hire_date")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(24);

                    b.Property<string>("PostalCode")
                        .HasColumnName("postal_code")
                        .HasMaxLength(10);

                    b.Property<int>("ReportsTo");

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasMaxLength(40);

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasMaxLength(30);

                    b.HasKey("EmployeeId")
                        .HasName("employee__employee_id__pkey");

                    b.HasIndex("ReportsTo");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("genre_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(120);

                    b.HasKey("GenreId")
                        .HasName("genre__genre_id__pkey");

                    b.ToTable("genre");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("invoice_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BillingAddress")
                        .HasColumnName("billing_address")
                        .HasMaxLength(70);

                    b.Property<string>("BillingCity")
                        .HasColumnName("billing_city")
                        .HasMaxLength(40);

                    b.Property<string>("BillingCountry")
                        .HasColumnName("billing_country")
                        .HasMaxLength(40);

                    b.Property<string>("BillingPostalCode")
                        .HasColumnName("billing_postal_code")
                        .HasMaxLength(10);

                    b.Property<string>("BillingState")
                        .HasColumnName("billing_state")
                        .HasMaxLength(40);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnName("invoice_date")
                        .HasColumnType("date");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("total")
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValueSql("0");

                    b.HasKey("InvoiceId")
                        .HasName("invoice_id_pkey");

                    b.HasIndex("CustomerId")
                        .HasName("invoice__customer_id__idx");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.InvoiceLine", b =>
                {
                    b.Property<int>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("invoice_line_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("InvoiceId");

                    b.Property<int>("Quantity")
                        .HasColumnName("quantity");

                    b.Property<int>("TrackId");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("unit_price")
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValueSql("0");

                    b.HasKey("InvoiceLineId")
                        .HasName("invoice_line__invoice_line_id__pkey");

                    b.HasIndex("InvoiceId")
                        .HasName("invoice_line__invoice_id__idx");

                    b.HasIndex("TrackId")
                        .HasName("invoice_line__track_id__idx");

                    b.ToTable("invoice_line");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.MediaType", b =>
                {
                    b.Property<int>("MediaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("media_type_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(120);

                    b.HasKey("MediaTypeId")
                        .HasName("media_type__media_type_id__pkey");

                    b.ToTable("media_type");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("playlist_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(120);

                    b.HasKey("PlaylistId")
                        .HasName("playlist__playlist_id__pkey");

                    b.ToTable("playlist");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.PlaylistTrack", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnName("PlaylistId");

                    b.Property<int>("TrackId")
                        .HasColumnName("TrackId");

                    b.HasKey("PlaylistId", "TrackId")
                        .HasName("playlist_track__playlist_track_id__pkey");

                    b.HasIndex("TrackId")
                        .HasName("playlist_track__track_id__idx");

                    b.ToTable("playlist_track");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("track_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AlbumId");

                    b.Property<int>("Bytes")
                        .HasColumnName("bytes");

                    b.Property<string>("Composer")
                        .HasColumnName("composer")
                        .HasMaxLength(220);

                    b.Property<int?>("GenreId");

                    b.Property<int>("MediaTypeId");

                    b.Property<int>("Milliseconds")
                        .HasColumnName("milliseconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(120);

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("unit_price")
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("TrackId")
                        .HasName("track__track_id__pkey");

                    b.HasIndex("AlbumId")
                        .HasName("track__album_id__idx");

                    b.HasIndex("GenreId")
                        .HasName("track__genre_id__idx");

                    b.HasIndex("MediaTypeId")
                        .HasName("track__media_type_id__idx");

                    b.ToTable("track");
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Album", b =>
                {
                    b.HasOne("Chinook.WebApi.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("Album__reference_artist__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Customer", b =>
                {
                    b.HasOne("Chinook.WebApi.Models.Employee", "SupportRep")
                        .WithMany("Customers")
                        .HasForeignKey("SupportRepId")
                        .HasConstraintName("customer__reference_employee__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Employee", b =>
                {
                    b.HasOne("Chinook.WebApi.Models.Employee", "ReportsToManager")
                        .WithMany("EmployeesInCharge")
                        .HasForeignKey("ReportsTo")
                        .HasConstraintName("employee__reference_employee__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Invoice", b =>
                {
                    b.HasOne("Chinook.WebApi.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("invoice__reference_customer_id__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Chinook.WebApi.Models.InvoiceLine", b =>
                {
                    b.HasOne("Chinook.WebApi.Models.Invoice", "Invoice")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("invoice_line__reference_invoice_id__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Chinook.WebApi.Models.Track", "Track")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("invoice_line__reference_track_id__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Chinook.WebApi.Models.PlaylistTrack", b =>
                {
                    b.HasOne("Chinook.WebApi.Models.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .HasConstraintName("playlist_track__reference_playlist__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Chinook.WebApi.Models.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("playlist_track__reference_track__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Chinook.WebApi.Models.Track", b =>
                {
                    b.HasOne("Chinook.WebApi.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("track__reference_album_id__fkey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Chinook.WebApi.Models.Genre", "Genre")
                        .WithMany("Tracks")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("track__reference_genre_id__fkey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Chinook.WebApi.Models.MediaType", "MediaType")
                        .WithMany("Tracks")
                        .HasForeignKey("MediaTypeId")
                        .HasConstraintName("track__reference_media_type_id__fkey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
